service: ${self:custom.config.service-name}

plugins:
  - serverless-offline
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./serverless-yml/environment.yml)}
  iamRoleStatements:
    - ${file(./serverless-yml/iamRoleStatements/dynamodbUserInfo.yml)}
    - ${file(./serverless-yml/iamRoleStatements/sesAndS3.yml)}

custom: ${file(./serverless-yml/custom.yml)}

functions: ${file(./serverless-dynamic.js):functions}

resources:
  Resources: ${file(./serverless-dynamic.js):resources}
  Outputs: ${file(./serverless-yml/outputs.yml)}
