service: ${self:custom.config.service-name}

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./serverless-yml/environment.yml)}
  iamRoleStatements:
    - ${file(./serverless-yml/iamRoleStatements/dynamodbUserInfo.yml)}
    - ${file(./serverless-yml/iamRoleStatements/sesAndS3.yml)}

custom: ${file(./serverless-yml/custom.yml)}

package:
  individually: true

functions: ${file(./serverless-dynamic.js):functions}

resources:
  Resources: ${file(./serverless-dynamic.js):resources}
  # Print out the name of the bucket that is created. Buckets are global, name is randomly generated.
  Outputs:
    AttachmentsBucketName:
      Value:
        Ref: AttachmentsBucket
