service: ${self:custom.config.service-name}

plugins:
  - serverless-plugin-common-excludes
  - serverless-plugin-include-dependencies

provider:
  name: aws
  runtime: nodejs12.x
  environment: ${file(./serverless-yml/environment.yml)}
  iamRoleStatements: ${file(./temp/iamRoleStatements.yml)}

custom: ${file(./serverless-yml/custom.yml)}

functions: ${file(./temp/functions.yml)}

resources:
  Resources: ${file(./temp/resources.yml)}
